# in Powershell: needs "$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1"
# https://github.com/jwilder/nginx-proxy/issues/1110
version: '3'

services:
  docker-restarter:
    build: .
    image: docker-restarter:0.1.0
    container_name: docker-restarter
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: php -S 0.0.0.0:80 -t /app/public

  test:
    container_name: test
    image: nginx:latest